# version: '3'
# services:
#   postgres:
#     image: postgres:9.6
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=postgres
#     volumes:
#       - data:/var/lib/postgresql/data
#       - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
#     env_file:
#       - config/.env
      
#   pg-admin:
#     image: dpage/pgadmin4:6
#     ports:
#       - "5050:5050"
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@email.com
#       - PGADMIN_DEFAULT_PASSWORD=admin
#       - PGADMIN_LISTEN_PORT=5050
  
#   nginx:
#     restart: always
#     build:
#       dockerfile: Dockerfile.dev
#       context: ./nginx
#     ports:
#       - '3050:80'
      
#   api:
#     build:
#       context: ./server
#       dockerfile: Dockerfile.dev
#     restart: always
#     ports:
#       - 5000:5000
#     volumes:
#       - /server:/server
#       - /server/node_modules  
      
#   client:
#     build:
#       context: ./client
#       dockerfile: Dockerfile.dev
#     restart: always
#     volumes:
#       - /app/node_modules
#       - ./client:/app

# volumes:
#   data:


version: '3'
services:

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      # - MYSQL_ROOT_PASSWORD=mysqldb
      # - MYSQL_DATABASE=mysqldb
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    volumes:
      - db:/var/lib/mysql
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "3050:80"
  

  api:
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      # - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      # - DB_HOST=localhost
      # - DB_USER=mysqldb
      # - DB_PASSWORD=mysqldb
      # - DB_NAME=mysqldb
      # - DB_PORT=3306
      - JWT_SECRET=$JWT_SECRET
      - FINNHUB_API_KEY=$FINNHUB_API_KEY
      
  client:
    build: ./client
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  db:
