version: '3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgresql/data
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - config/.env
      
  pg-admin:
    image: dpage/pgadmin4:6
    ports:
      - "5050:5050"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
  
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
      
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /server:/server
      - /server/node_modules  
      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - /app/node_modules
      - ./client:/app

volumes:
  data:
