version: '3'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
      
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /server:/server
      - /server/node_modules  
      
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - /app/node_modules
      - ./client:/app