version: '3'
services:

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
  
  nginx:
    build: ./nginx
    restart: unless-stopped
    # expose:
    #   - 3050:3050
    ports:
      - "80:80"
  

  api:
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $API_LOCAL_PORT:$API_DOCKER_URL 
      # - "5000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - JWT_SECRET=$JWT_SECRET
      - FINNHUB_API_KEY=$FINNHUB_API_KEY
      - CLIENT_ORIGIN=$DOCKER_CLIENT_ORIGIN # http://localhost:3000
    # networks:
    #   - Frontend
    #   - Backend
      
  client:
    build: 
      context: ./client
      args:
        - REACT_APP_API_ORIGIN=$API_ORIGIN
    restart: unless-stopped
    ports:
      # - $REACT_LOCAL_PORT:$REACT_DOCKER_URL #
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    # networks:
    #   - Frontend

volumes:
  db:

# networks:
#   Frontend:
#   Backend:

